### ISSUE TITLE
Allow passing non interactive options

### ISSUE THREAD

**Issue by ihattab** [NdagiStanley/vue-django#534]

**Comment by ihattab** [comment]
docker-compose -f docker-compose.yml up  OUPUT 
sastec@sastec:~/vueJs$ docker-compose -f docker-compose.yml up 
Building vuejs
Step 1/12 : FROM node:9-stretch
9-stretch: Pulling from library/node
55cbf04beb70: Already exists
1607093a898c: Already exists
9a8ea045c926: Already exists
d4eee24d4dac: Already exists
b59856e9f0ab: Pull complete
d6cd23cd1a2c: Pull complete
00d0f45dd25b: Pull complete
211e677cc869: Pull complete
fbe49c17a613: Pull complete
Digest: sha256:07b483e788713ae0362d77ca26e078f8335dfc0df6d84d4be18acd58f7b09768
Status: Downloaded newer image for node:9-stretch
 ---> 7de06a6ac6db
Step 2/12 : RUN apt-get update && apt-get install -y expect
 ---> Running in bd07f7a78e76
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:3 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2365 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [505 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.4 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7086 kB]
Fetched 7924 kB in 2s (2871 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2
  libfontenc1 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libllvm3.9
  libpciaccess0 libsensors4 libtcl8.6 libtk8.6 libtxc-dxtn-s2tc libutempter0
  libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-shape0 libxcb-sync1 libxft2 libxmu6 libxmuu1 libxshmfence1 libxss1
  libxtst6 libxv1 libxxf86dga1 libxxf86vm1 tcl-expect tcl8.6 tk8.6 x11-utils
  xbitmaps xterm
Suggested packages:
  pciutils lm-sensors tcl-tclreadline mesa-utils xfonts-cyrillic
The following NEW packages will be installed:
  expect libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2
  libfontenc1 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libllvm3.9
  libpciaccess0 libsensors4 libtcl8.6 libtk8.6 libtxc-dxtn-s2tc libutempter0
  libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-shape0 libxcb-sync1 libxft2 libxmu6 libxmuu1 libxshmfence1 libxss1
  libxtst6 libxv1 libxxf86dga1 libxxf86vm1 tcl-expect tcl8.6 tk8.6 x11-utils
  xbitmaps xterm
0 upgraded, 40 newly installed, 0 to remove and 96 not upgraded.
Need to get 20.8 MB of archives.
After this operation, 177 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 libxss1 amd64 1:1.2.2-1 [17.5 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 libtcl8.6 amd64 8.6.6+dfsg-1+b1 [985 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 tcl-expect amd64 5.45-7+deb9u1 [131 kB]
Get:4 http://deb.debian.org/debian stretch/main amd64 expect amd64 5.45-7+deb9u1 [165 kB]
Get:5 http://deb.debian.org/debian stretch/main amd64 libdrm2 amd64 2.4.74-1 [36.2 kB]
Get:6 http://deb.debian.org/debian stretch/main amd64 libdrm-amdgpu1 amd64 2.4.74-1 [26.4 kB]
Get:7 http://deb.debian.org/debian stretch/main amd64 libpciaccess0 amd64 0.13.4-1+b2 [50.0 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 libdrm-intel1 amd64 2.4.74-1 [68.7 kB]
Get:9 http://deb.debian.org/debian stretch/main amd64 libdrm-nouveau2 amd64 2.4.74-1 [25.1 kB]
Get:10 http://deb.debian.org/debian stretch/main amd64 libdrm-radeon1 amd64 2.4.74-1 [30.2 kB]
Get:11 http://deb.debian.org/debian stretch/main amd64 libfontenc1 amd64 1:1.1.3-1+b2 [24.4 kB]
Get:12 http://deb.debian.org/debian stretch/main amd64 libllvm3.9 amd64 1:3.9.1-9 [11.3 MB]
Get:13 http://deb.debian.org/debian stretch/main amd64 libsensors4 amd64 1:3.4.0-4 [53.3 kB]
Get:14 http://deb.debian.org/debian stretch/main amd64 libgl1-mesa-dri amd64 13.0.6-1+b2 [4536 kB]
Get:15 http://deb.debian.org/debian stretch/main amd64 libglapi-mesa amd64 13.0.6-1+b2 [58.9 kB]
Get:16 http://deb.debian.org/debian stretch/main amd64 libx11-xcb1 amd64 2:1.6.4-3+deb9u1 [183 kB]
Get:17 http://deb.debian.org/debian stretch/main amd64 libxcb-dri2-0 amd64 1.12-1 [97.2 kB]
Get:18 http://deb.debian.org/debian stretch/main amd64 libxcb-dri3-0 amd64 1.12-1 [95.6 kB]
Get:19 http://deb.debian.org/debian stretch/main amd64 libxcb-glx0 amd64 1.12-1 [113 kB]
Get:20 http://deb.debian.org/debian stretch/main amd64 libxcb-present0 amd64 1.12-1 [95.8 kB]
Get:21 http://deb.debian.org/debian stretch/main amd64 libxcb-sync1 amd64 1.12-1 [99.2 kB]
Get:22 http://deb.debian.org/debian stretch/main amd64 libxshmfence1 amd64 1.2-1+b2 [7922 B]
Get:23 http://deb.debian.org/debian stretch/main amd64 libxxf86vm1 amd64 1:1.1.4-1+b2 [20.8 kB]
Get:24 http://deb.debian.org/debian stretch/main amd64 libgl1-mesa-glx amd64 13.0.6-1+b2 [167 kB]
Get:25 http://deb.debian.org/debian stretch/main amd64 libxft2 amd64 2.3.2-1+b2 [56.5 kB]
Get:26 http://deb.debian.org/debian stretch/main amd64 libtk8.6 amd64 8.6.6-1+b1 [754 kB]
Get:27 http://deb.debian.org/debian stretch/main amd64 libutempter0 amd64 1.1.6-3 [7812 B]
Get:28 http://deb.debian.org/debian stretch/main amd64 libxmu6 amd64 2:1.1.2-2 [60.3 kB]
Get:29 http://deb.debian.org/debian stretch/main amd64 libxaw7 amd64 2:1.0.13-1+b2 [201 kB]
Get:30 http://deb.debian.org/debian stretch/main amd64 libxcb-shape0 amd64 1.12-1 [96.2 kB]
Get:31 http://deb.debian.org/debian stretch/main amd64 libxmuu1 amd64 2:1.1.2-2 [23.5 kB]
Get:32 http://deb.debian.org/debian stretch/main amd64 libxtst6 amd64 2:1.2.3-1 [27.8 kB]
Get:33 http://deb.debian.org/debian stretch/main amd64 libxv1 amd64 2:1.0.11-1 [24.6 kB]
Get:34 http://deb.debian.org/debian stretch/main amd64 libxxf86dga1 amd64 2:1.1.4-1+b3 [22.1 kB]
Get:35 http://deb.debian.org/debian stretch/main amd64 tcl8.6 amd64 8.6.6+dfsg-1+b1 [123 kB]
Get:36 http://deb.debian.org/debian stretch/main amd64 tk8.6 amd64 8.6.6-1+b1 [71.8 kB]
Get:37 http://deb.debian.org/debian stretch/main amd64 x11-utils amd64 7.7+3+b1 [202 kB]
Get:38 http://deb.debian.org/debian stretch/main amd64 xbitmaps all 1.1.1-2 [32.1 kB]
Get:39 http://deb.debian.org/debian stretch/main amd64 xterm amd64 327-2 [663 kB]
Get:40 http://deb.debian.org/debian stretch/main amd64 libtxc-dxtn-s2tc amd64 1.0+git20151227-2 [48.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 20.8 MB in 2s (8404 kB/s)
Selecting previously unselected package libxss1:amd64.
(Reading database ... 29648 files and directories currently installed.)
Preparing to unpack .../00-libxss1_1%3a1.2.2-1_amd64.deb ...
Unpacking libxss1:amd64 (1:1.2.2-1) ...
Selecting previously unselected package libtcl8.6:amd64.
Preparing to unpack .../01-libtcl8.6_8.6.6+dfsg-1+b1_amd64.deb ...
Unpacking libtcl8.6:amd64 (8.6.6+dfsg-1+b1) ...
Selecting previously unselected package tcl-expect:amd64.
Preparing to unpack .../02-tcl-expect_5.45-7+deb9u1_amd64.deb ...
Unpacking tcl-expect:amd64 (5.45-7+deb9u1) ...
Selecting previously unselected package expect.
Preparing to unpack .../03-expect_5.45-7+deb9u1_amd64.deb ...
Unpacking expect (5.45-7+deb9u1) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../04-libdrm2_2.4.74-1_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.74-1) ...
Selecting previously unselected package libdrm-amdgpu1:amd64.
Preparing to unpack .../05-libdrm-amdgpu1_2.4.74-1_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.74-1) ...
Selecting previously unselected package libpciaccess0:amd64.
Preparing to unpack .../06-libpciaccess0_0.13.4-1+b2_amd64.deb ...
Unpacking libpciaccess0:amd64 (0.13.4-1+b2) ...
Selecting previously unselected package libdrm-intel1:amd64.
Preparing to unpack .../07-libdrm-intel1_2.4.74-1_amd64.deb ...
Unpacking libdrm-intel1:amd64 (2.4.74-1) ...
Selecting previously unselected package libdrm-nouveau2:amd64.
Preparing to unpack .../08-libdrm-nouveau2_2.4.74-1_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.74-1) ...
Selecting previously unselected package libdrm-radeon1:amd64.
Preparing to unpack .../09-libdrm-radeon1_2.4.74-1_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.74-1) ...
Selecting previously unselected package libfontenc1:amd64.
Preparing to unpack .../10-libfontenc1_1%3a1.1.3-1+b2_amd64.deb ...
Unpacking libfontenc1:amd64 (1:1.1.3-1+b2) ...
Selecting previously unselected package libllvm3.9:amd64.
Preparing to unpack .../11-libllvm3.9_1%3a3.9.1-9_amd64.deb ...
Unpacking libllvm3.9:amd64 (1:3.9.1-9) ...
Selecting previously unselected package libsensors4:amd64.
Preparing to unpack .../12-libsensors4_1%3a3.4.0-4_amd64.deb ...
Unpacking libsensors4:amd64 (1:3.4.0-4) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../13-libgl1-mesa-dri_13.0.6-1+b2_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (13.0.6-1+b2) ...
Selecting previously unselected package libglapi-mesa:amd64.
Preparing to unpack .../14-libglapi-mesa_13.0.6-1+b2_amd64.deb ...
Unpacking libglapi-mesa:amd64 (13.0.6-1+b2) ...
Selecting previously unselected package libx11-xcb1:amd64.
Preparing to unpack .../15-libx11-xcb1_2%3a1.6.4-3+deb9u1_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.6.4-3+deb9u1) ...
Selecting previously unselected package libxcb-dri2-0:amd64.
Preparing to unpack .../16-libxcb-dri2-0_1.12-1_amd64.deb ...
Unpacking libxcb-dri2-0:amd64 (1.12-1) ...
Selecting previously unselected package libxcb-dri3-0:amd64.
Preparing to unpack .../17-libxcb-dri3-0_1.12-1_amd64.deb ...
Unpacking libxcb-dri3-0:amd64 (1.12-1) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../18-libxcb-glx0_1.12-1_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.12-1) ...
Selecting previously unselected package libxcb-present0:amd64.
Preparing to unpack .../19-libxcb-present0_1.12-1_amd64.deb ...
Unpacking libxcb-present0:amd64 (1.12-1) ...
Selecting previously unselected package libxcb-sync1:amd64.
Preparing to unpack .../20-libxcb-sync1_1.12-1_amd64.deb ...
Unpacking libxcb-sync1:amd64 (1.12-1) ...
Selecting previously unselected package libxshmfence1:amd64.
Preparing to unpack .../21-libxshmfence1_1.2-1+b2_amd64.deb ...
Unpacking libxshmfence1:amd64 (1.2-1+b2) ...
Selecting previously unselected package libxxf86vm1:amd64.
Preparing to unpack .../22-libxxf86vm1_1%3a1.1.4-1+b2_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1+b2) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../23-libgl1-mesa-glx_13.0.6-1+b2_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (13.0.6-1+b2) ...
Selecting previously unselected package libxft2:amd64.
Preparing to unpack .../24-libxft2_2.3.2-1+b2_amd64.deb ...
Unpacking libxft2:amd64 (2.3.2-1+b2) ...
Selecting previously unselected package libtk8.6:amd64.
Preparing to unpack .../25-libtk8.6_8.6.6-1+b1_amd64.deb ...
Unpacking libtk8.6:amd64 (8.6.6-1+b1) ...
Selecting previously unselected package libutempter0:amd64.
Preparing to unpack .../26-libutempter0_1.1.6-3_amd64.deb ...
Unpacking libutempter0:amd64 (1.1.6-3) ...
Selecting previously unselected package libxmu6:amd64.
Preparing to unpack .../27-libxmu6_2%3a1.1.2-2_amd64.deb ...
Unpacking libxmu6:amd64 (2:1.1.2-2) ...
Selecting previously unselected package libxaw7:amd64.
Preparing to unpack .../28-libxaw7_2%3a1.0.13-1+b2_amd64.deb ...
Unpacking libxaw7:amd64 (2:1.0.13-1+b2) ...
Selecting previously unselected package libxcb-shape0:amd64.
Preparing to unpack .../29-libxcb-shape0_1.12-1_amd64.deb ...
Unpacking libxcb-shape0:amd64 (1.12-1) ...
Selecting previously unselected package libxmuu1:amd64.
Preparing to unpack .../30-libxmuu1_2%3a1.1.2-2_amd64.deb ...
Unpacking libxmuu1:amd64 (2:1.1.2-2) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../31-libxtst6_2%3a1.2.3-1_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1) ...
Selecting previously unselected package libxv1:amd64.
Preparing to unpack .../32-libxv1_2%3a1.0.11-1_amd64.deb ...
Unpacking libxv1:amd64 (2:1.0.11-1) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../33-libxxf86dga1_2%3a1.1.4-1+b3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.4-1+b3) ...
Selecting previously unselected package tcl8.6.
Preparing to unpack .../34-tcl8.6_8.6.6+dfsg-1+b1_amd64.deb ...
Unpacking tcl8.6 (8.6.6+dfsg-1+b1) ...
Selecting previously unselected package tk8.6.
Preparing to unpack .../35-tk8.6_8.6.6-1+b1_amd64.deb ...
Unpacking tk8.6 (8.6.6-1+b1) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../36-x11-utils_7.7+3+b1_amd64.deb ...
Unpacking x11-utils (7.7+3+b1) ...
Selecting previously unselected package xbitmaps.
Preparing to unpack .../37-xbitmaps_1.1.1-2_all.deb ...
Unpacking xbitmaps (1.1.1-2) ...
Selecting previously unselected package xterm.
Preparing to unpack .../38-xterm_327-2_amd64.deb ...
Unpacking xterm (327-2) ...
Selecting previously unselected package libtxc-dxtn-s2tc:amd64.
Preparing to unpack .../39-libtxc-dxtn-s2tc_1.0+git20151227-2_amd64.deb ...
Unpacking libtxc-dxtn-s2tc:amd64 (1.0+git20151227-2) ...
Setting up libxcb-present0:amd64 (1.12-1) ...
Setting up libxcb-dri2-0:amd64 (1.12-1) ...
Setting up libxcb-dri3-0:amd64 (1.12-1) ...
Setting up libxcb-glx0:amd64 (1.12-1) ...
Processing triggers for mime-support (3.60) ...
Setting up xbitmaps (1.1.1-2) ...
Setting up libxss1:amd64 (1:1.2.2-1) ...
Setting up libxshmfence1:amd64 (1.2-1+b2) ...
Setting up libllvm3.9:amd64 (1:3.9.1-9) ...
Setting up libtxc-dxtn-s2tc:amd64 (1.0+git20151227-2) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/s2tc/libtxc_dxtn.so to provide /usr/lib/x86_64-linux-gnu/libtxc_dxtn.so (libtxc-dxtn-x86_64-linux-gnu) in auto mode
Setting up libglapi-mesa:amd64 (13.0.6-1+b2) ...
Setting up libxmuu1:amd64 (2:1.1.2-2) ...
Setting up libutempter0:amd64 (1.1.6-3) ...
Setting up libxtst6:amd64 (2:1.2.3-1) ...
Setting up libxmu6:amd64 (2:1.1.2-2) ...
Setting up libdrm2:amd64 (2.4.74-1) ...
Setting up libxcb-sync1:amd64 (1.12-1) ...
Setting up libx11-xcb1:amd64 (2:1.6.4-3+deb9u1) ...
Setting up libxxf86dga1:amd64 (2:1.1.4-1+b3) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Setting up libfontenc1:amd64 (1:1.1.3-1+b2) ...
Setting up libxcb-shape0:amd64 (1.12-1) ...
Setting up libpciaccess0:amd64 (0.13.4-1+b2) ...
Setting up libxv1:amd64 (2:1.0.11-1) ...
Setting up libsensors4:amd64 (1:3.4.0-4) ...
Setting up libdrm-radeon1:amd64 (2.4.74-1) ...
Setting up libtcl8.6:amd64 (8.6.6+dfsg-1+b1) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1+b2) ...
Setting up libdrm-nouveau2:amd64 (2.4.74-1) ...
Setting up libxft2:amd64 (2.3.2-1+b2) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Setting up libxaw7:amd64 (2:1.0.13-1+b2) ...
Setting up libdrm-amdgpu1:amd64 (2.4.74-1) ...
Setting up libtk8.6:amd64 (8.6.6-1+b1) ...
Setting up xterm (327-2) ...
update-alternatives: using /usr/bin/xterm to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode
update-alternatives: using /usr/bin/lxterm to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode
Setting up libdrm-intel1:amd64 (2.4.74-1) ...
Setting up libgl1-mesa-glx:amd64 (13.0.6-1+b2) ...
Setting up tcl-expect:amd64 (5.45-7+deb9u1) ...
Setting up tcl8.6 (8.6.6+dfsg-1+b1) ...
Setting up expect (5.45-7+deb9u1) ...
Setting up tk8.6 (8.6.6-1+b1) ...
Setting up libgl1-mesa-dri:amd64 (13.0.6-1+b2) ...
Setting up x11-utils (7.7+3+b1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Removing intermediate container bd07f7a78e76
 ---> 9b43bbc61094
Step 3/12 : RUN npm install -g vue-cli
 ---> Running in b96059c00a4f
npm WARN deprecated vue-cli@2.9.6: This package has been deprecated in favour of @vue/cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list
+ vue-cli@2.9.6
added 241 packages in 17.396s
Removing intermediate container b96059c00a4f
 ---> 69bd36ce246c
Step 4/12 : WORKDIR /usr/local/
 ---> Running in fa7469272652
Removing intermediate container fa7469272652
 ---> bacc60ac091a
Step 5/12 : COPY ./vue-cli-interaction.exp /usr/local/vue-cli-interaction.exp
 ---> e6d887443a12
Step 6/12 : RUN ls -la
 ---> Running in b9a4072bb087
total 192
drwxrwsr-x 21 root staff  4096 Sep 19 08:01 .
drwxr-xr-x 38 root root   4096 Sep 19 08:01 ..
-rw-rw-r--  1 root staff 54115 Jun 12  2018 CHANGELOG.md
-rw-rw-r--  1 root staff 62033 Jun 12  2018 LICENSE
-rw-rw-r--  1 root staff 27805 Jun 12  2018 README.md
drwxrwxr-x  2 root staff  4096 Sep 19 08:01 bin
drwxrwsr-x  2 root staff  4096 Jul 16  2018 etc
drwxrwsr-x  2 root staff  4096 Jul 16  2018 games
drwxrwxr-x  3 root staff  4096 Jun 12  2018 include
drwxrwxr-x  6 root staff  4096 Sep 19 08:01 lib
lrwxrwxrwx  1 root staff     9 Jul 16  2018 man -> share/man
drwxrwsr-x  2 root staff  4096 Jul 16  2018 sbin
drwxrwxr-x  8 root staff  4096 Jun 12  2018 share
drwxrwsr-x  2 root staff  4096 Jul 16  2018 src
-rw-r--r--  1 root root    269 Sep 18 16:51 vue-cli-interaction.exp
Removing intermediate container b9a4072bb087
 ---> 40b28a7ea61c
Step 7/12 : CMD ["vue-cli-interaction.exp"]
 ---> Running in c49f5553968d
Removing intermediate container c49f5553968d
 ---> c49786c1579a
Step 8/12 : WORKDIR /usr/local/app
 ---> Running in ab7bdc6d15bd
Removing intermediate container ab7bdc6d15bd
 ---> 585f9fa0979e
Step 9/12 : RUN ls -la
 ---> Running in fd270de26566
total 8
drwxr-sr-x  2 root root  4096 Sep 19 08:01 .
drwxrwsr-x 22 root staff 4096 Sep 19 08:01 ..
Removing intermediate container fd270de26566
 ---> 643c1202f2e1
Step 10/12 : RUN npm install && npm dedupe
 ---> Running in c1625c982fb3
npm WARN saveError ENOENT: no such file or directory, open '/usr/local/app/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.

up to date in 0.082s
npm WARN saveError ENOENT: no such file or directory, open '/usr/local/app/package.json'
up to date in 0.035s
Removing intermediate container c1625c982fb3
 ---> 272a869eca0f
Step 11/12 : EXPOSE 3000
 ---> Running in a609aae523d0
Removing intermediate container a609aae523d0
 ---> fc2ec4f05c97
Step 12/12 : ENTRYPOINT /opt/entrypoint.sh
 ---> Running in 3f25e9b6fa86
Removing intermediate container 3f25e9b6fa86
 ---> 8c3f387a43dd
Successfully built 8c3f387a43dd
Successfully tagged vuejs:latest
WARNING: Image for service vuejs was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating vuejs ... done
Attaching to vuejs
vuejs    | vue-cli-interaction.exp: 1: vue-cli-interaction.exp: /opt/entrypoint.sh: not found
vuejs exited with code 127
sastec@sastec:~/vueJs$ docker-compose ps
Name               Command                State     Ports
---------------------------------------------------------
vuejs   /bin/sh -c /opt/entrypoint ...   Exit 127

**Comment by NdagiStanley** [comment]
@ihattab could you explain the issue here.
