### ISSUE TITLE
Django 2 install broken

### ISSUE THREAD

**Issue by rambii** [NdagiStanley/vue-django#74]
As I already commented on issue #12 the current state of the develop branch is broken as far as I can tell.

I couldn't install django 2 correctly as the Dockerfile is currently using python 2 instead of 3. I worked it out. Let me know if you are interested in a pull request.

**Comment by NdagiStanley** [comment]
Hey @rambii 
Happy Holidays.

A PR is always welcome.

**Comment by NdagiStanley** [comment]
Hi @rambii 
I had a quick run of this. At first I thought that the update to 2.0 for Django was breaking it. I have confirmed that it is A-Okay and it runs well.

About the `Dockerfile` here's a [PR](https://github.com/NdagiStanley/vue-django/pull/84) to fix this.
