### ISSUE TITLE
Placement of static files

### ISSUE THREAD

**Issue by qarthandgi** [NdagiStanley/vue-django#75]
I'm attempting to place a .js file from Font Awesome in the `index.html` `head` tag to be available to the whole app, per [these instructions](https://fontawesome.com/get-started).

I figured I should place the downloaded `js` file in `/static` folder but it doesn't seem to be bringing it over the `/staticfiles` folder to be found by `index.html` when it's time to load the page.

Where in the directory should I be placing these header `<script>` files in `index.html` that will make them be automatically built correctly?

**Comment by GarrettArm** [comment]
After 'python manage.py collectstatic', all my static files grouped into the folder {BASE_DIR}/staticfiles -- which I'm happy with.

But in "templates/index.html", with my build, I had to replace all the strings "static" with "staticfiles".  

Can't promise this doesn't break something downstream, but at least the index.html finds those static files.  

I.e.,
<script type=text/javascript src=/staticfiles/js/manifest.{some_long_identifier}.js</script>


While we're on this topic, you may choose to put a 'python manage.py migrate' in the deploy.sh.  Maybe that's harmful -- I don't know.  It was a small hurdle before the server would run.
